workflows:
  rxSwiftTrial-workflow:
    name: rxSwiftTrial Pipeline
    scripts:
        - name: CICD Startup
          script: echo "welcome to ci cd setup"
    publishing:
      email:
        recipients:
          - lionato14@gmail.com  